const settings = document.createElement('script');
settings.type = 'text/javascript';
settings.src = 'settings.js';
document.head.appendChild(settings);
const classes = document.createElement('script');
classes.type = 'text/javascript';
classes.src = 'classes.js';
document.head.appendChild(classes);
const script = document.createElement('script');
script.type = 'text/javascript';
script.src = 'script.js';
document.head.appendChild(script);